version: ':latest'
services:

  phpsite:
    image: php:apache
    command: php -S 0.0.0.0:80
    ports:
      - "8080:80"
    volumes:
      - /mnt/Pool/webserver:/var/www/html
  
  nodejs:
    image: node:alpine
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - /mnt/Pool/webserver:/var/www/html
    depends_on:
      - php
    command: ["node", "index"]
